<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="LAPTOP-BVIUIKAG" name="com.orangeHRM.testcases.orangeHRM_login" tests="5" failures="1" timestamp="16 Jul 2021 11:29:20 GMT" time="52.016" errors="0">
  <testcase name="validatewebelement" time="18.520" classname="com.orangeHRM.testcases.orangeHRM_login"/>
  <testcase name="validate" time="8.915" classname="com.orangeHRM.testcases.orangeHRM_login">
    <failure type="java.lang.AssertionError" message="expected [sam] but found [OrangeHRM]">
      <![CDATA[java.lang.AssertionError: expected [sam] but found [OrangeHRM]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.orangeHRM.testcases.Golden_template.ValidatePageTitle(Golden_template.java:123)
at com.orangeHRM.testcases.orangeHRM_login.validate(orangeHRM_login.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validate -->
  <testcase name="validate" time="9.269" classname="com.orangeHRM.testcases.orangeHRM_login">
    <skipped/>
  </testcase> <!-- validate -->
  <testcase name="validate" time="7.464" classname="com.orangeHRM.testcases.orangeHRM_login">
    <skipped/>
  </testcase> <!-- validate -->
  <testcase name="validate" time="7.848" classname="com.orangeHRM.testcases.orangeHRM_login">
    <skipped/>
  </testcase> <!-- validate -->
</testsuite> <!-- com.orangeHRM.testcases.orangeHRM_login -->
